export enum ErrorCode {
    INVALID_DATA = "INVALID_DATA",
    DOUBLE_REPORT = "DOUBLE_REPORT",
    MEASURE_NOT_FOUND = "MEASURE_NOT_FOUND",
    CONFIRMATION_DUPLICATE = "CONFIRMATION_DUPLICATE",
    INVALID_TYPE = "INVALID_TYPE",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
}